***This file runs all balance sheet regressions in the paper.
*This requires access to CRSP, Compustat, and CIQ to work.

*** Tables 5 and B-14 to B-19

clear
use basequarterly

*Capital t+1.
qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
outreg2 using capital, tex replace label dec(2)

*Capital t+2 to t+8.
foreach var of varlist chcapfix2-chcapfix8{
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
outreg2 using capital, tex append label dec(2)
}

*Net worth t+1.
qui reghdfe chnetworthfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
outreg2 using networth, tex replace label dec(2)

*Net worth t+2 to t+8.
foreach var of varlist chnetworthfix2-chnetworthfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
outreg2 using networth, tex append label dec(2)
}

*Total assets t+1.
qui reghdfe changetotass1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using asset, tex replace label dec(2)

*Total assets t+2 to t+8.
foreach var of varlist changetotass2-changetotass8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using asset, tex append label dec(2)
}
 
*Total liabilities t+1.
qui reghdfe chsumdebtfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using debt, tex replace label dec(2)

*Total liabilities t+2 to t+8.
foreach var of varlist  chsumdebtfix2-chsumdebtfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using debt, tex append label dec(2)
}
  
*Inventory t+1.
qui reghdfe chinvfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using inventory, tex replace label dec(2)

*Inventory t+2 to t+8.
foreach var of varlist chinvfix2-chinvfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using inventory, tex append label dec(2)
}
 
*Cash holding t+1.
qui reghdfe chcashfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag  c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using cash, tex replace label dec(2)

*Cash holding t+2 to t+8.
foreach var of varlist chcashfix2-chcashfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag, absorb(gvkey period) vce(cluster period) 
outreg2 using cash, tex append label dec(2)
}

*Marginal effects.
su matvarasslag, d

qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#i.hedgeindlag c.changeavr#c.matvarasslag#i.zlbdummy c.changeavr#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#i.hedgeindlag c.changetarg#c.matvarasslag#i.zlbdummy c.changetarg#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag  c.matvarasslag#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.54 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.14 divpersharelag=0.20 cashtoaslag=0.095 profitabilitylag=0.03 changetarg=0.02 matvarasslag=2.48) post noestimcheck

qui reghdfe chcapfix4 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#i.hedgeindlag c.changeavr#c.matvarasslag#i.zlbdummy c.changeavr#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#i.hedgeindlag c.changetarg#c.matvarasslag#i.zlbdummy c.changetarg#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag  c.matvarasslag#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.54 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.14 divpersharelag=0.20 cashtoaslag=0.095 profitabilitylag=0.03 changetarg=0.02 matvarasslag=2.48) post noestimcheck

qui reghdfe chcapfix5 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#i.hedgeindlag c.changeavr#c.matvarasslag#i.zlbdummy c.changeavr#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#i.hedgeindlag c.changetarg#c.matvarasslag#i.zlbdummy c.changetarg#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag  c.matvarasslag#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.54 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.14 divpersharelag=0.20 cashtoaslag=0.095 profitabilitylag=0.03 changetarg=0.02 matvarasslag=2.48) post noestimcheck

qui reghdfe chcapfix8 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#i.hedgeindlag c.changeavr#c.matvarasslag#i.zlbdummy c.changeavr#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#i.hedgeindlag c.changetarg#c.matvarasslag#i.zlbdummy c.changetarg#c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changeavr#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag  c.matvarasslag#i.hedgeindlag c.matvarasslag#i.hedgeindlag#i.zlbdummy c.changetarg#i.hedgeindlag#i.zlbdummy c.matvarasslag#i.zlbdummy i.hedgeindlag#i.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.54 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.14 divpersharelag=0.20 cashtoaslag=0.095 profitabilitylag=0.03 changetarg=0.02 matvarasslag=2.48) post noestimcheck

*** Tables 6 and B-20 to B-21
 
gen fincon=laggedaveragefcp

*Capital t+1.
qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
outreg2 using finconcapital, tex replace label dec(2)

*Capital t+2 to t+8.
foreach var of varlist chcapfix2-chcapfix8{
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy  c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
outreg2 using finconcapital, tex append label dec(2)
}

*Net worth t+1.
qui reghdfe chnetworthfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag  c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
outreg2 using finconnetworth, tex replace label dec(2)

*Net worth t+2 to t+8.
foreach var of varlist chnetworthfix2-chnetworthfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy  c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(gvkey period) vce(cluster period) 
outreg2 using finconnetworth, tex append label dec(2)
}

*Marginal effects. 
su laggedaveragefcp, d

*At the median.
qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.48 matvarasslag=2.48) post noestimcheck

*Constrained firm.
qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.16 matvarasslag=2.48) post noestimcheck

*At the median.
qui reghdfe chcapfix4 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.48 matvarasslag=2.48 )  post noestimcheck

*Constrained firm.
qui reghdfe chcapfix4 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.16 matvarasslag=2.48) post noestimcheck

*At the median.
qui reghdfe chcapfix5 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.48 matvarasslag=2.48 ) post noestimcheck

*Constrained firm.
qui reghdfe chcapfix5 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.16 matvarasslag=2.48) post noestimcheck

*At the median.
qui reghdfe chcapfix8 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.48 matvarasslag=2.48 ) post noestimcheck

*Constrained firm.
qui reghdfe chcapfix8 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(gvkey period) vce(cluster period) 
margins, dydx(changeavr) over(hedgeindlag zlbdummy) at(sizelag=4.53 markettobooklag=1.55 booklevlag=0.54 solfinlag=0.03 assetmatlag=64 reqtoaslag=0.13 divpersharelag=0.20 cashtoaslag=0.09 profitabilitylag=0.03 changetarg=0.02 fincon=-1.16 matvarasslag=2.48) post noestimcheck
