***This file demonstrates our main regressions with pseudo data sets. 
*This, by design, will not reproduce our results.

clear
import excel "C:\Users\gokce\Desktop\pseudostock.xlsx", sheet("Sheet1") firstrow

*** Stock return regressions

*Note: We get the same results if we use reghdfe instead. 

*Table 3:
*Only firm fixed effects.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using table3, tex replace label dec(2)

*Only time fixed effects.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(numstock) vce(cluster numstock) 
outreg2 using table3, tex append label dec(2)

*Both firm and time fixed effects.
qui areg twodaypercprccd i.numstock c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using table3, tex append label dec(2)

*Table 4:
*Age dummy.
qui areg twodaypercprccd i.numstock c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy##1.agedum c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy##1.agedum c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.sizelag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.profitabilitylag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.profitabilitylag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.booklevlag##1.hedgeindlag##1.zlbdummy c.transfact2##c.booklevlag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.markettobooklag##1.hedgeindlag##1.zlbdummy c.transfact2##c.markettobooklag##1.hedgeindlag##1.zlbdummy c.transfact1##c.cashtoaslag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.cashtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.assetmat##1.hedgeindlag##1.zlbdummy  c.transfact2##c.assetmat##1.hedgeindlag##1.zlbdummy c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy, absorb(firmnumber) vce(cluster numstock) 
outreg2 using table4, tex replace label dec(2)

*Large changes in exposure.
qui areg twodaypercprccd i.numstock c.transfact2##c.matvarasslag##1.dumchexppos##1.hedgeindlag##1.zlbdummy c.transfact1##c.matvarasslag##1.dumchexppos##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.dumchexpneg##1.hedgeindlag##1.zlbdummy c.transfact1##c.matvarasslag##1.dumchexpneg##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.sizelag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.profitabilitylag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.profitabilitylag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.booklevlag##1.hedgeindlag##1.zlbdummy c.transfact2##c.booklevlag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.markettobooklag##1.hedgeindlag##1.zlbdummy c.transfact2##c.markettobooklag##1.hedgeindlag##1.zlbdummy c.transfact1##c.cashtoaslag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.cashtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.assetmat##1.hedgeindlag##1.zlbdummy  c.transfact2##c.assetmat##1.hedgeindlag##1.zlbdummy c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy, absorb(firmnumber) vce(cluster numstock) 
outreg2 using table4, tex append label dec(2)

*Current and lagged exposure.
qui areg twodaypercprccd i.numstock c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.matvarasslag15##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag15##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.sizelag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.profitabilitylag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.profitabilitylag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.booklevlag##1.hedgeindlag##1.zlbdummy c.transfact2##c.booklevlag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.markettobooklag##1.hedgeindlag##1.zlbdummy c.transfact2##c.markettobooklag##1.hedgeindlag##1.zlbdummy c.transfact1##c.cashtoaslag##1.hedgeindlag##1.zlbdummy  c.transfact2##c.cashtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.assetmat##1.hedgeindlag##1.zlbdummy  c.transfact2##c.assetmat##1.hedgeindlag##1.zlbdummy c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy, absorb(firmnumber) vce(cluster numstock) 
outreg2 using table4, tex append label dec(2)

*Table B9:
*Floating rate debt leverage.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.varlevorlag##1.hedgeindlag##1.zlbdummy c.transfact2##c.varlevorlag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb9, tex replace label dec(2)

*Bank debt leverage and excess return.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag twowinmkt, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb9, tex append label dec(2)

*Floating rate debt leverage and excess return.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.varlevorlag##1.hedgeindlag##1.zlbdummy c.transfact2##c.varlevorlag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag twowinmkt, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb9, tex append label dec(2)

*Bank debt leverage and Fama-French adjustments.
qui areg famadjret c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb9, tex append label dec(2)

*Bank debt leverage and Fama-French adjustments, with controls.
qui areg famadjret c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb9, tex append label dec(2)

*Floating rate debt and Fama-French adjustments, without controls.
qui areg famadjret c.transfact1##c.varlevorlag##1.hedgeindlag##1.zlbdummy c.transfact2##c.varlevorlag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb9, tex append label dec(2)

*Table B-10:
*One-day window.
qui areg percprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb10, tex replace label dec(2)

*Fixed rate debt exposure.
qui areg twodaypercprccd c.transfact1##c.matfixasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matfixasslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock)
outreg2 using tableb10, tex append label dec(2)

*Only scheduled FOMC meetings.
drop if intermeetdummy==1
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy  c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb10, tex append label dec(2)

*Table B-11:
*Maturity based on known debt types.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##1.hedgeindlag##1.zlbdummy##c.matallassknowlag c.transfact2##1.hedgeindlag##1.zlbdummy##c.matallassknowlag c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb11, tex replace label dec(2)

*Maturity based on known debt types, with time fixed effects.
qui areg twodaypercprccd i.numstock c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##1.hedgeindlag##1.zlbdummy##c.matallassknowlag c.transfact2##1.hedgeindlag##1.zlbdummy##c.matallassknowlag c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb11, tex append label dec(2)

*Maturity based on all debt types.
qui areg twodaypercprccd  c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##1.hedgeindlag##1.zlbdummy##c.matallasslag c.transfact2##1.hedgeindlag##1.zlbdummy##c.matallasslag c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb11, tex append label dec(2)

*Maturity based on all debt types, with time fixed effects.
qui areg twodaypercprccd i.numstock c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##1.hedgeindlag##1.zlbdummy##c.matallasslag c.transfact2##1.hedgeindlag##1.zlbdummy##c.matallasslag c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb11, tex append label dec(2)

*Simple average maturity.
qui areg twodaypercprccd c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##1.hedgeindlag##1.zlbdummy##c.avrmatlag c.transfact2##1.hedgeindlag##1.zlbdummy##c.avrmatlag c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb11, tex append label dec(2)

*Simple average maturity, with time fixed effects.
qui areg twodaypercprccd i.numstock c.transfact1##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.reqtoaslag##1.hedgeindlag##1.zlbdummy c.transfact1##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact2##c.divpersharelag##1.hedgeindlag##1.zlbdummy c.transfact1##c.newbankratiolag##1.hedgeindlag##1.zlbdummy c.transfact2##c.newbankratiolag##1.hedgeindlag##1.zlbdummy   c.transfact1##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact2##c.matvarasslag##1.hedgeindlag##1.zlbdummy c.transfact1##1.hedgeindlag##1.zlbdummy##c.avrmatlag c.transfact2##1.hedgeindlag##1.zlbdummy##c.avrmatlag c.transfact1##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.sizelag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.profitabilitylag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.profitabilitylag##1.zlbdummy##1.hedgeindlag   c.transfact1##c.booklevlag##1.zlbdummy##1.hedgeindlag c.transfact2##c.booklevlag##1.zlbdummy##1.hedgeindlag  c.transfact1##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact2##c.markettobooklag##1.zlbdummy##1.hedgeindlag c.transfact1##c.cashtoaslag##1.zlbdummy##1.hedgeindlag  c.transfact2##c.cashtoaslag##1.zlbdummy##1.hedgeindlag c.transfact1##c.assetmat##1.zlbdummy##1.hedgeindlag  c.transfact2##c.assetmat##1.zlbdummy##1.hedgeindlag, absorb(firmnumber) vce(cluster numstock) 
outreg2 using tableb11, tex append label dec(2)

*Table B-12:
*IV regression.
ivreghdfe twodaypercprccd transfact1 transfact2  c.transfact1#c.assetmat c.transfact2#c.assetmat assetmat c.transfact1#c.sizelag  c.transfact2#c.sizelag sizelag c.transfact1#c.profitabilitylag  c.transfact2#c.profitabilitylag profitabilitylag   c.transfact1#c.booklevlag c.transfact2#c.booklevlag booklevlag c.transfact1#c.markettobooklag c.transfact2#c.markettobooklag markettobooklag c.transfact1#c.cashtoaslag  c.transfact2#c.cashtoaslag cashtoaslag c.transfact1#c.reqtoaslag c.transfact2#c.reqtoaslag reqtoaslag c.transfact1#c.divpersharelag c.transfact2#c.divpersharelag divpersharelag (matvarasslag c.transfact1#c.matvarasslag c.transfact2#c.matvarasslag = matvarasslag15 c.transfact1#c.matvarasslag15 c.transfact2#c.matvarasslag15), absorb(firmnumber)
outreg2 using tableb12, tex replace label dec(2)


*** Balance sheet regressions

clear
import excel "C:\Users\gokce\Desktop\pseudobalance.xlsx", sheet("Sheet1") firstrow

*Capital t+1.
qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(firmnumber period) vce(cluster period) 
outreg2 using capital, tex replace label dec(2)

*Capital t+2 to t+8.
foreach var of varlist chcapfix2-chcapfix8{
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(firmnumber period) vce(cluster period) 
outreg2 using capital, tex append label dec(2)
}

*Net worth t+1.
qui reghdfe chnetworthfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(firmnumber period) vce(cluster period) 
outreg2 using networth, tex replace label dec(2)

*Net worth t+2 to t+8.
foreach var of varlist chnetworthfix2-chnetworthfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(firmnumber period) vce(cluster period) 
outreg2 using networth, tex append label dec(2)
}

*Total assets t+1.
qui reghdfe changetotass1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using asset, tex replace label dec(2)

*Total assets t+2 to t+8.
foreach var of varlist changetotass2-changetotass8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using asset, tex append label dec(2)
}
 
*Total liabilities t+1.
qui reghdfe chsumdebtfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using debt, tex replace label dec(2)

*Total liabilities t+2 to t+8.
foreach var of varlist  chsumdebtfix2-chsumdebtfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using debt, tex append label dec(2)
}
  
*Inventory t+1.
qui reghdfe chinvfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using inventory, tex replace label dec(2)

*Inventory t+2 to t+8.
foreach var of varlist chinvfix2-chinvfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag,  absorb(firmnumber period) vce(cluster period) 
outreg2 using inventory, tex append label dec(2)
}
 
*Cash holding t+1.
qui reghdfe chcashfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag  c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using cash, tex replace label dec(2)

*Cash holding t+2 to t+8.
foreach var of varlist chcashfix2-chcashfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag, absorb(firmnumber period) vce(cluster period) 
outreg2 using cash, tex append label dec(2)
}

*** Balance sheet regressions with financial constraints

*Capital t+1.
qui reghdfe chcapfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(firmnumber period) vce(cluster period) 
outreg2 using finconcapital, tex replace label dec(2)

*Capital t+2 to t+8.
foreach var of varlist chcapfix2-chcapfix8{
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy  c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changeavr#c.reqtoaslag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy, absorb(firmnumber period) vce(cluster period) 
outreg2 using finconcapital, tex append label dec(2)
}

*Net worth t+1.
qui reghdfe chnetworthfix1 c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag  c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag, absorb(firmnumber period) vce(cluster period) 
outreg2 using finconnetworth, tex replace label dec(2)

*Net worth t+2 to t+8.
foreach var of varlist chnetworthfix2-chnetworthfix8 {
qui reghdfe  `var' c.changeavr#c.matvarasslag c.changeavr#c.matvarasslag#1.hedgeindlag c.changeavr#c.matvarasslag#1.zlbdummy c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag c.fincon#c.changeavr#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr#c.matvarasslag#1.hedgeindlag#1.zlbdummy  c.changetarg#c.matvarasslag c.changetarg#c.matvarasslag#1.hedgeindlag c.changetarg#c.matvarasslag#1.zlbdummy c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag  c.matvarasslag#1.hedgeindlag c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changetarg#1.hedgeindlag#1.zlbdummy c.matvarasslag#1.zlbdummy 1.hedgeindlag#1.zlbdummy matvarasslag hedgeindlag   c.fincon c.fincon#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag#1.zlbdummy c.fincon#1.hedgeindlag#1.zlbdummy c.fincon#c.changeavr#1.zlbdummy c.fincon#c.changeavr#1.hedgeindlag c.fincon#c.matvarasslag#1.hedgeindlag c.fincon#c.matvarasslag#1.zlbdummy c.fincon#c.changeavr c.fincon#c.matvarasslag c.fincon#1.hedgeindlag c.fincon#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.zlbdummy c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag c.fincon#c.changetarg#c.matvarasslag c.fincon#c.changetarg#1.zlbdummy c.fincon#c.changetarg#1.hedgeindlag c.fincon#c.changetarg c.fincon#c.changetarg#c.matvarasslag#1.hedgeindlag#1.zlbdummy c.changeavr#c.sizelag sizelag c.changeavr#c.markettobooklag markettobooklag c.changeavr#c.booklevlag booklevlag c.changeavr#c.solfinlag solfinlag c.changeavr#c.profitabilitylag profitabilitylag c.changetarg#c.sizelag c.changetarg#c.markettobooklag c.changetarg#c.booklevlag c.changetarg#c.solfinlag c.changetarg#c.profitabilitylag c.changeavr#c.assetmatlag assetmatlag c.changetarg#c.assetmatlag c.changeavr#c.reqtoaslag reqtoaslag c.changetarg#c.reqtoaslag c.changeavr#c.divpersharelag divpersharelag c.changetarg#c.divpersharelag c.changeavr#c.cashtoaslag cashtoaslag c.changetarg#c.cashtoaslag,  absorb(firmnumber period) vce(cluster period) 
outreg2 using finconnetworth, tex append label dec(2)
}
